//! Classifier rule registry (Phase 2, Step 2.3).
//!
//! Every classifier rule is a static, compile-time entry. Rules are referenced
//! by `rule_id` string from [`Evidence`](crate::model::Evidence) and from the
//! corpus `metadata.json`. `format` is a `&'static str` (not `ArchiveFormat`)
//! so the registry can cover all 12 corpus formats, not just the four the
//! engine parses today.

use crate::model::{CorruptionCategory, EvidenceType, Severity};

/// A single classifier rule.
#[derive(Debug, Clone, Copy)]
pub struct ClassifierRule {
    pub id: &'static str,
    pub format: &'static str,
    pub category: CorruptionCategory,
    pub default_severity: Severity,
    pub description: &'static str,
    pub affected_field: &'static str,
    pub evidence_type: EvidenceType,
    /// `true` ⇒ confidence is always 1.0 (signature/offset checks).
    pub confidence_deterministic: bool,
}

/// Look up a rule by id.
pub fn rule(id: &str) -> Option<&'static ClassifierRule> {
    RULES.iter().find(|r| r.id == id)
}

use CorruptionCategory as C;
use EvidenceType as E;
use Severity as S;

/// Compile-time-complete rule registry covering the Phase 1 check matrices.
pub static RULES: &[ClassifierRule] = &[
    // ── ZIP ──────────────────────────────────────────────────────────────
    r(
        "ZIP_EOCD_001",
        "ZIP",
        C::StructuralCorruption,
        S::Catastrophic,
        "EOCD signature missing or zeroed",
        "EOCD.signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ZIP_EOCD_002",
        "ZIP",
        C::StructuralCorruption,
        S::Major,
        "EOCD.cd_offset points outside file",
        "EOCD.cd_offset",
        E::OffsetOutOfBounds,
        false,
    ),
    r(
        "ZIP_EOCD_003",
        "ZIP",
        C::StructuralCorruption,
        S::Major,
        "EOCD.cd_size larger than file",
        "EOCD.cd_size",
        E::LengthOverflow,
        true,
    ),
    r(
        "ZIP_CD_001",
        "ZIP",
        C::StructuralCorruption,
        S::Catastrophic,
        "Central directory entirely missing",
        "CentralDirectory",
        E::StructureMissing,
        false,
    ),
    r(
        "ZIP_CD_002",
        "ZIP",
        C::StructuralCorruption,
        S::Major,
        "Central directory signature invalid",
        "CentralDirHeader.signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ZIP_CD_003",
        "ZIP",
        C::MissingData,
        S::Major,
        "Central directory truncated mid-entry",
        "CentralDirectory",
        E::TruncationMarker,
        false,
    ),
    r(
        "ZIP_LFH_001",
        "ZIP",
        C::StructuralCorruption,
        S::Major,
        "Local file header signature invalid",
        "LocalFileHeader.signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ZIP_LFH_002",
        "ZIP",
        C::MissingData,
        S::Major,
        "Local file header missing",
        "LocalFileHeader",
        E::StructureMissing,
        false,
    ),
    r(
        "ZIP_CRC_001",
        "ZIP",
        C::ChecksumMismatch,
        S::Minor,
        "CRC-32 mismatch, single entry",
        "LocalFileHeader.crc32",
        E::ChecksumMismatch,
        true,
    ),
    r(
        "ZIP_CRC_002",
        "ZIP",
        C::ChecksumMismatch,
        S::Major,
        "CRC-32 mismatch, multiple entries",
        "LocalFileHeader.crc32",
        E::ChecksumMismatch,
        true,
    ),
    r(
        "ZIP_SIZE_001",
        "ZIP",
        C::StructuralCorruption,
        S::Major,
        "Compressed size field wrong (too large)",
        "CentralDirHeader.compressed_size",
        E::LengthOverflow,
        false,
    ),
    r(
        "ZIP_SIZE_002",
        "ZIP",
        C::Truncation,
        S::Major,
        "File shorter than declared compressed size",
        "stream",
        E::TruncationMarker,
        false,
    ),
    r(
        "ZIP_TRUNC_001",
        "ZIP",
        C::Truncation,
        S::Minor,
        "Truncated last 1%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "ZIP_TRUNC_002",
        "ZIP",
        C::Truncation,
        S::Major,
        "Truncated last 5%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "ZIP_TRUNC_003",
        "ZIP",
        C::Truncation,
        S::Catastrophic,
        "Truncated last 20%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "ZIP_TRUNC_004",
        "ZIP",
        C::Truncation,
        S::Catastrophic,
        "Truncated first 5% (header destroyed)",
        "stream.header",
        E::TruncationMarker,
        false,
    ),
    r(
        "ZIP_FLIP_001",
        "ZIP",
        C::BitFlip,
        S::Minor,
        "Single bit flip in payload",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "ZIP_FLIP_002",
        "ZIP",
        C::BitFlip,
        S::Major,
        "Multiple bit flips in payload",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "ZIP_FLIP_003",
        "ZIP",
        C::BitFlip,
        S::Major,
        "Bit flip in header area",
        "header.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "ZIP_EXTRA_001",
        "ZIP",
        C::StructuralCorruption,
        S::Minor,
        "Extra field length overflow",
        "CentralDirHeader.extra_len",
        E::LengthOverflow,
        false,
    ),
    r(
        "ZIP_Z64_001",
        "ZIP",
        C::StructuralCorruption,
        S::Major,
        "ZIP64 EOCD locator corrupted",
        "ZIP64_EOCD_Locator.signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ZIP_COMP_001",
        "ZIP",
        C::StructuralCorruption,
        S::Catastrophic,
        "Compound: missing EOCD + CRC mismatch",
        "EOCD.signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ZIP_COMP_002",
        "ZIP",
        C::Truncation,
        S::Catastrophic,
        "Compound: truncated + bitflip",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    // ── TAR ──────────────────────────────────────────────────────────────
    r(
        "TAR_UST_001",
        "TAR",
        C::StructuralCorruption,
        S::Major,
        "UStar checksum invalid",
        "UStarHeader.checksum",
        E::ChecksumMismatch,
        true,
    ),
    r(
        "TAR_UST_002",
        "TAR",
        C::StructuralCorruption,
        S::Minor,
        "UStar magic missing",
        "UStarHeader.magic",
        E::SignatureMismatch,
        true,
    ),
    r(
        "TAR_TERM_001",
        "TAR",
        C::StructuralCorruption,
        S::Minor,
        "Missing zero-block terminator",
        "Archive.terminator",
        E::StructureMissing,
        false,
    ),
    r(
        "TAR_TERM_002",
        "TAR",
        C::PaddingMismatch,
        S::Benign,
        "Extra garbage after terminator",
        "Archive.terminator",
        E::PaddingViolation,
        false,
    ),
    r(
        "TAR_SIZE_001",
        "TAR",
        C::StructuralCorruption,
        S::Major,
        "Size field larger than remaining data",
        "UStarHeader.size",
        E::LengthOverflow,
        false,
    ),
    r(
        "TAR_SIZE_002",
        "TAR",
        C::MissingData,
        S::Major,
        "File data shorter than declared size",
        "UStarHeader.size",
        E::TruncationMarker,
        false,
    ),
    r(
        "TAR_BLOCK_001",
        "TAR",
        C::BlockReorder,
        S::Major,
        "Two data blocks swapped",
        "block.order",
        E::BlockReorder,
        false,
    ),
    r(
        "TAR_TRUNC_001",
        "TAR",
        C::Truncation,
        S::Minor,
        "Truncated last 1%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "TAR_TRUNC_002",
        "TAR",
        C::Truncation,
        S::Major,
        "Truncated last 10%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "TAR_TRUNC_003",
        "TAR",
        C::Truncation,
        S::Catastrophic,
        "Truncated first block",
        "stream.header",
        E::TruncationMarker,
        false,
    ),
    r(
        "TAR_FLIP_001",
        "TAR",
        C::BitFlip,
        S::Minor,
        "Single bit flip in file content",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "TAR_FLIP_002",
        "TAR",
        C::BitFlip,
        S::Major,
        "Multiple bit flips in header area",
        "header.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "TAR_GNU_001",
        "TAR",
        C::StructuralCorruption,
        S::Major,
        "GNU LongName block corrupted",
        "GnuLongName.block",
        E::StructureMissing,
        false,
    ),
    r(
        "TAR_SPARSE_001",
        "TAR",
        C::StructuralCorruption,
        S::Major,
        "Sparse file map invalid",
        "SparseMap",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "TAR_COMP_001",
        "TAR",
        C::StructuralCorruption,
        S::Catastrophic,
        "Compound: checksum + truncated",
        "UStarHeader.checksum",
        E::ChecksumMismatch,
        true,
    ),
    // ── ISO 9660 ─────────────────────────────────────────────────────────
    r(
        "ISO_PVD_001",
        "ISO",
        C::StructuralCorruption,
        S::Catastrophic,
        "Primary volume descriptor magic missing",
        "PrimaryVolumeDescriptor.magic",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ISO_PVD_002",
        "ISO",
        C::StructuralCorruption,
        S::Major,
        "PVD volume space size wrong",
        "PrimaryVolumeDescriptor.volume_space",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "ISO_SVD_001",
        "ISO",
        C::StructuralCorruption,
        S::Major,
        "Supplementary VD (Joliet) corrupt",
        "SupplementaryVolumeDescriptor.magic",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ISO_PT_001",
        "ISO",
        C::MissingData,
        S::Major,
        "Path table offset beyond EOF",
        "PrimaryVolumeDescriptor.path_table_location",
        E::OffsetOutOfBounds,
        false,
    ),
    r(
        "ISO_PT_002",
        "ISO",
        C::StructuralCorruption,
        S::Major,
        "Path table entry length invalid",
        "PathTable.entry_length",
        E::LengthUnderflow,
        false,
    ),
    r(
        "ISO_DIR_001",
        "ISO",
        C::StructuralCorruption,
        S::Major,
        "Directory record length field zero",
        "DirectoryRecord.length",
        E::LengthUnderflow,
        false,
    ),
    r(
        "ISO_DIR_002",
        "ISO",
        C::MissingData,
        S::Major,
        "Directory record points to missing extent",
        "DirectoryRecord.extent",
        E::OffsetOutOfBounds,
        false,
    ),
    r(
        "ISO_SECTOR_001",
        "ISO",
        C::BitFlip,
        S::Minor,
        "Single sector data bitflip",
        "sector.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "ISO_SECTOR_002",
        "ISO",
        C::MissingData,
        S::Major,
        "Multiple consecutive sectors zeroed",
        "sector.data",
        E::StructureMissing,
        false,
    ),
    r(
        "ISO_TRUNC_001",
        "ISO",
        C::Truncation,
        S::Major,
        "Truncated 5%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "ISO_TRUNC_002",
        "ISO",
        C::Truncation,
        S::Catastrophic,
        "Truncated 20%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "ISO_TRUNC_003",
        "ISO",
        C::Truncation,
        S::Catastrophic,
        "Truncated at PVD (sector 16)",
        "stream.header",
        E::TruncationMarker,
        false,
    ),
    // ── GZIP ─────────────────────────────────────────────────────────────
    r(
        "GZ_MAGIC_001",
        "GZIP",
        C::StructuralCorruption,
        S::Catastrophic,
        "Magic bytes replaced",
        "gzip.magic",
        E::SignatureMismatch,
        true,
    ),
    r(
        "GZ_CM_001",
        "GZIP",
        C::StructuralCorruption,
        S::Major,
        "Compression method invalid (not 8)",
        "gzip.cm",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "GZ_HCRC_001",
        "GZIP",
        C::ChecksumMismatch,
        S::Minor,
        "Header CRC16 mismatch",
        "gzip.hcrc",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "GZ_ICRC_001",
        "GZIP",
        C::ChecksumMismatch,
        S::Major,
        "Content CRC32 mismatch",
        "gzip.crc32",
        E::ChecksumMismatch,
        true,
    ),
    r(
        "GZ_ISIZE_001",
        "GZIP",
        C::StructuralCorruption,
        S::Minor,
        "ISIZE wrong",
        "gzip.isize",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "GZ_TRUNC_001",
        "GZIP",
        C::Truncation,
        S::Major,
        "Truncated in compressed data",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "GZ_TRUNC_002",
        "GZIP",
        C::Truncation,
        S::Catastrophic,
        "Truncated before header end",
        "stream.header",
        E::TruncationMarker,
        false,
    ),
    r(
        "GZ_FLIP_001",
        "GZIP",
        C::BitFlip,
        S::Major,
        "Bit flip in compressed data",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "GZ_EXTRA_001",
        "GZIP",
        C::StructuralCorruption,
        S::Minor,
        "Extra field length overflow",
        "gzip.extra_len",
        E::LengthOverflow,
        false,
    ),
    // ── PDF (stubs; parser is a later phase) ─────────────────────────────
    r(
        "PDF_HDR_001",
        "PDF",
        C::StructuralCorruption,
        S::Catastrophic,
        "%PDF- header missing",
        "pdf.header",
        E::SignatureMismatch,
        true,
    ),
    r(
        "PDF_HDR_002",
        "PDF",
        C::StructuralCorruption,
        S::Minor,
        "Version marker malformed",
        "pdf.version",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "PDF_EOF_001",
        "PDF",
        C::StructuralCorruption,
        S::Major,
        "%%EOF marker missing",
        "pdf.eof",
        E::StructureMissing,
        false,
    ),
    r(
        "PDF_XREF_001",
        "PDF",
        C::StructuralCorruption,
        S::Major,
        "startxref offset wrong",
        "pdf.startxref",
        E::OffsetOutOfBounds,
        false,
    ),
    r(
        "PDF_XREF_002",
        "PDF",
        C::MissingData,
        S::Major,
        "xref table missing entirely",
        "pdf.xref",
        E::StructureMissing,
        false,
    ),
    r(
        "PDF_XREF_003",
        "PDF",
        C::StructuralCorruption,
        S::Major,
        "xref entry format invalid",
        "pdf.xref.entry",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "PDF_OBJ_001",
        "PDF",
        C::StructuralCorruption,
        S::Major,
        "Object stream header corrupt",
        "pdf.objstm",
        E::StructureMissing,
        false,
    ),
    r(
        "PDF_OBJ_002",
        "PDF",
        C::MissingData,
        S::Major,
        "Indirect object missing",
        "pdf.object",
        E::StructureMissing,
        false,
    ),
    r(
        "PDF_TRUNC_001",
        "PDF",
        C::Truncation,
        S::Minor,
        "Truncated last 1%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "PDF_TRUNC_002",
        "PDF",
        C::Truncation,
        S::Major,
        "Truncated last 15%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "PDF_TRUNC_003",
        "PDF",
        C::Truncation,
        S::Catastrophic,
        "Truncated at 50%",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "PDF_FLIP_001",
        "PDF",
        C::BitFlip,
        S::Minor,
        "Bit flip in page content stream",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "PDF_FLIP_002",
        "PDF",
        C::BitFlip,
        S::Major,
        "Bit flip in cross-reference stream",
        "pdf.xref.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "PDF_COMP_001",
        "PDF",
        C::StructuralCorruption,
        S::Catastrophic,
        "Missing xref + object missing",
        "pdf.xref",
        E::StructureMissing,
        false,
    ),
    // ── SQLite (stubs; parser is a later phase) ──────────────────────────
    r(
        "SQ_MAGIC_001",
        "SQLite",
        C::StructuralCorruption,
        S::Catastrophic,
        "Header magic missing",
        "sqlite.magic",
        E::SignatureMismatch,
        true,
    ),
    r(
        "SQ_PGSIZE_001",
        "SQLite",
        C::StructuralCorruption,
        S::Catastrophic,
        "Page size not a power of two",
        "sqlite.page_size",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_PGSIZE_002",
        "SQLite",
        C::StructuralCorruption,
        S::Major,
        "Page size mismatch with actual pages",
        "sqlite.page_size",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_FC_001",
        "SQLite",
        C::StructuralCorruption,
        S::Major,
        "File change counter mismatch",
        "sqlite.change_counter",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_BTREE_001",
        "SQLite",
        C::StructuralCorruption,
        S::Major,
        "B-tree page type byte invalid",
        "sqlite.btree.page_type",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_BTREE_002",
        "SQLite",
        C::StructuralCorruption,
        S::Major,
        "B-tree cell count exceeds capacity",
        "sqlite.btree.cell_count",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_BTREE_003",
        "SQLite",
        C::MissingData,
        S::Major,
        "Cell pointer references missing offset",
        "sqlite.btree.cell_ptr",
        E::OffsetOutOfBounds,
        false,
    ),
    r(
        "SQ_FREE_001",
        "SQLite",
        C::StructuralCorruption,
        S::Minor,
        "Freelist trunk page number invalid",
        "sqlite.freelist_trunk",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_FREE_002",
        "SQLite",
        C::StructuralCorruption,
        S::Major,
        "Freelist count exceeds actual pages",
        "sqlite.freelist_count",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_WAL_001",
        "SQLite",
        C::StructuralCorruption,
        S::Minor,
        "WAL header magic missing",
        "wal.magic",
        E::SignatureMismatch,
        true,
    ),
    r(
        "SQ_WAL_002",
        "SQLite",
        C::StructuralCorruption,
        S::Major,
        "WAL salt mismatch",
        "wal.salt",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SQ_TRUNC_001",
        "SQLite",
        C::Truncation,
        S::Major,
        "Truncated mid-page",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "SQ_TRUNC_002",
        "SQLite",
        C::Truncation,
        S::Catastrophic,
        "Truncated before page 2",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "SQ_FLIP_001",
        "SQLite",
        C::BitFlip,
        S::Minor,
        "Bit flip in row data",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "SQ_FLIP_002",
        "SQLite",
        C::BitFlip,
        S::Major,
        "Bit flip in B-tree interior key",
        "sqlite.btree.key",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "SQ_COMP_001",
        "SQLite",
        C::StructuralCorruption,
        S::Catastrophic,
        "Corrupt B-tree + bit flip",
        "sqlite.btree",
        E::StructureMissing,
        false,
    ),
    // ── Generic stream-format rules (RAR/7Z/BZ2/XZ/ZSTD/LZ4) ─────────────
    r(
        "RAR_MAGIC_001",
        "RAR",
        C::StructuralCorruption,
        S::Catastrophic,
        "RAR signature corrupted",
        "signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "RAR_CRC_001",
        "RAR",
        C::ChecksumMismatch,
        S::Major,
        "RAR file CRC mismatch",
        "trailer.checksum",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "7Z_MAGIC_001",
        "7Z",
        C::StructuralCorruption,
        S::Catastrophic,
        "7z signature header corrupted",
        "signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "7Z_CRC_001",
        "7Z",
        C::ChecksumMismatch,
        S::Major,
        "7z CRC mismatch",
        "trailer.checksum",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "7Z_TRUNC_001",
        "7Z",
        C::Truncation,
        S::Catastrophic,
        "7z end header beyond EOF (truncated)",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "BZ2_MAGIC_001",
        "BZIP2",
        C::StructuralCorruption,
        S::Catastrophic,
        "BZh stream magic corrupted",
        "signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "BZ2_CRC_001",
        "BZIP2",
        C::ChecksumMismatch,
        S::Major,
        "BZIP2 block CRC mismatch",
        "trailer.checksum",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "XZ_MAGIC_001",
        "XZ",
        C::StructuralCorruption,
        S::Catastrophic,
        "XZ stream header magic corrupted",
        "signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "XZ_CRC_001",
        "XZ",
        C::ChecksumMismatch,
        S::Major,
        "XZ check mismatch",
        "trailer.checksum",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "ZST_MAGIC_001",
        "ZSTD",
        C::StructuralCorruption,
        S::Catastrophic,
        "ZSTD frame magic corrupted",
        "signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "ZST_CRC_001",
        "ZSTD",
        C::ChecksumMismatch,
        S::Major,
        "ZSTD content checksum mismatch",
        "trailer.checksum",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "LZ4_MAGIC_001",
        "LZ4",
        C::StructuralCorruption,
        S::Catastrophic,
        "LZ4 frame magic corrupted",
        "signature",
        E::SignatureMismatch,
        true,
    ),
    r(
        "LZ4_CRC_001",
        "LZ4",
        C::ChecksumMismatch,
        S::Major,
        "LZ4 content checksum mismatch",
        "trailer.checksum",
        E::ChecksumMismatch,
        false,
    ),
    // ── Cross-format ─────────────────────────────────────────────────────
    r(
        "INTEGRITY_HASH_001",
        "*",
        C::ChecksumMismatch,
        S::Major,
        "Content hash does not match manifest",
        "manifest.hash",
        E::ChecksumMismatch,
        true,
    ),
    r(
        "GEN_TRUNC_001",
        "*",
        C::Truncation,
        S::Major,
        "Stream truncated",
        "stream.tail",
        E::TruncationMarker,
        false,
    ),
    r(
        "GEN_FLIP_001",
        "*",
        C::BitFlip,
        S::Minor,
        "Flipped bit(s)",
        "payload.bits",
        E::ChecksumMismatch,
        false,
    ),
    r(
        "GEN_MISSING_001",
        "*",
        C::MissingData,
        S::Major,
        "Data region missing",
        "data.range",
        E::StructureMissing,
        false,
    ),
    r(
        "GEN_STRUCT_001",
        "*",
        C::StructuralCorruption,
        S::Major,
        "Structural corruption",
        "stream.layout",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "GEN_REORDER_001",
        "*",
        C::BlockReorder,
        S::Major,
        "Blocks out of order",
        "block.order",
        E::BlockReorder,
        false,
    ),
    // ── Security threats (Phase 0.5) ───────────────────────────────────────
    // Emitted by `phx_sandbox` during bounded traversal, not by the format
    // classifiers. They share the rule registry so reports key off them
    // identically to corruption findings.
    r(
        "SEC_BOMB_RATIO_001",
        "*",
        C::SecurityThreat,
        S::Catastrophic,
        "Compression ratio (per-entry or aggregate) exceeds limit",
        "decompress.ratio",
        E::RatioExceeded,
        false,
    ),
    r(
        "SEC_BOMB_OUTPUT_001",
        "*",
        C::SecurityThreat,
        S::Catastrophic,
        "Cumulative uncompressed output exceeds cap",
        "decompress.output_bytes",
        E::RatioExceeded,
        false,
    ),
    r(
        "SEC_BOMB_OVERLAP_001",
        "ZIP",
        C::SecurityThreat,
        S::Catastrophic,
        "Two local file headers reference overlapping data (Fifield signature)",
        "LocalFileHeader.compressed_data",
        E::OverlappingEntries,
        false,
    ),
    r(
        "SEC_CYCLE_001",
        "*",
        C::SecurityThreat,
        S::Catastrophic,
        "Nested container hash equals an ancestor's (quine)",
        "container.sha256",
        E::CycleDetected,
        true,
    ),
    r(
        "SEC_DEPTH_001",
        "*",
        C::SecurityThreat,
        S::Major,
        "Nesting depth exceeds max_depth",
        "container.depth",
        E::DepthExceeded,
        true,
    ),
    r(
        "SEC_ENTRIES_001",
        "*",
        C::SecurityThreat,
        S::Major,
        "Entry count exceeds limit",
        "container.entry_count",
        E::ValueOutOfRange,
        false,
    ),
    r(
        "SEC_TRAVERSAL_001",
        "*",
        C::SecurityThreat,
        S::Major,
        "Entry path escapes staging after normalization",
        "entry.path",
        E::PathEscape,
        true,
    ),
    r(
        "SEC_SYMLINK_001",
        "*",
        C::SecurityThreat,
        S::Major,
        "Symlink/hardlink entry pointing outside sandbox",
        "entry.link_target",
        E::PathEscape,
        true,
    ),
    r(
        "SEC_PARSER_TIMEOUT_001",
        "*",
        C::SecurityThreat,
        S::Major,
        "A parser exceeded its CPU-time budget on one container",
        "container.cpu_time",
        E::ValueOutOfRange,
        false,
    ),
];

/// Terse const constructor for a [`ClassifierRule`].
#[allow(clippy::too_many_arguments)]
const fn r(
    id: &'static str,
    format: &'static str,
    category: CorruptionCategory,
    default_severity: Severity,
    description: &'static str,
    affected_field: &'static str,
    evidence_type: EvidenceType,
    confidence_deterministic: bool,
) -> ClassifierRule {
    ClassifierRule {
        id,
        format,
        category,
        default_severity,
        description,
        affected_field,
        evidence_type,
        confidence_deterministic,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup_known_rule() {
        let rule = rule("ZIP_EOCD_001").unwrap();
        assert_eq!(rule.category, CorruptionCategory::StructuralCorruption);
        assert_eq!(rule.default_severity, Severity::Catastrophic);
    }

    #[test]
    fn unknown_rule_is_none() {
        assert!(rule("NOPE_999").is_none());
    }

    #[test]
    fn all_rule_ids_unique() {
        let mut ids: Vec<&str> = RULES.iter().map(|r| r.id).collect();
        ids.sort_unstable();
        let len = ids.len();
        ids.dedup();
        assert_eq!(ids.len(), len, "duplicate rule id in registry");
    }

    #[test]
    fn matrix_rule_ids_present() {
        for id in [
            "ZIP_CRC_001",
            "TAR_UST_001",
            "ISO_PVD_001",
            "GZ_MAGIC_001",
            "PDF_HDR_001",
            "SQ_MAGIC_001",
        ] {
            assert!(rule(id).is_some(), "missing {id}");
        }
    }

    #[test]
    fn security_rules_present_and_categorized() {
        for id in [
            "SEC_BOMB_RATIO_001",
            "SEC_BOMB_OUTPUT_001",
            "SEC_BOMB_OVERLAP_001",
            "SEC_CYCLE_001",
            "SEC_DEPTH_001",
            "SEC_ENTRIES_001",
            "SEC_TRAVERSAL_001",
            "SEC_SYMLINK_001",
            "SEC_PARSER_TIMEOUT_001",
        ] {
            let r = rule(id).unwrap_or_else(|| panic!("missing {id}"));
            assert_eq!(
                r.category,
                CorruptionCategory::SecurityThreat,
                "{id} must be a SecurityThreat"
            );
        }
    }
}
